import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "UPick (유픽) - 세상의 모든 극한 밸런스게임과 취향 분석 테스트",
  description: "로그인 없이 0초 만에 남녀노소 누구나 즐길 수 있는 밸런스게임! 당신의 선택을 보여주고, 실시간 통계를 확인해 보세요.",
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "UPick (유픽) - 세상의 모든 극한 밸런스게임과 취향 분석 테스트",
    description: "로그인 없이 0초 만에 남녀노소 누구나 즐길 수 있는 밸런스게임! 당신의 선택을 보여주고, 실시간 통계를 확인해 보세요.",
    url: "https://upick.kr",
    siteName: "UPick",
    images: [
      {
        url: "https://upick.kr/og-image.png",
        width: 1200,
        height: 630,
        alt: "UPick 밸런스 게임 대표 이미지",
      },
    ],
    locale: "ko_KR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "UPick (유픽) - 세상의 모든 극한 밸런스게임과 취향 분석 테스트",
    description: "로그인 없이 0초 만에 남녀노소 누구나 즐길 수 있는 밸런스게임! 당신의 선택을 보여주고, 실시간 통계를 확인해 보세요.",
    images: ["https://upick.kr/og-image.png"],
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full antialiased dark">
      <head>
        <meta name="naver-site-verification" content="aa867b3c75b1169bbf1474f38f3d20d18e83a4bc" />
        
        {/* Favicon package generated by Favicon.im Generator */}
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png" />
        <meta name="theme-color" content="#ffffff" />

        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.css"
        />
        {/* Google AdSense Verification Script */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3522634980237009"
          crossOrigin="anonymous"
        />
        {/* Kakao JavaScript SDK */}
        <script
          src="https://t1.kakaocdn.net/kakao_js_sdk/2.8.1/kakao.min.js"
          integrity="sha384-OL+ylM/iuPLtW5U3XcvLSGhE8JzReKDank5InqlHGWPhb4140/yrBw0bg0y7+C9J"
          crossOrigin="anonymous"
          async
        />
      </head>
      <body className="min-h-full bg-[#080911] text-white antialiased">
        {/* Google Analytics (GA4) Script */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-1EQTDJBSD4"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-1EQTDJBSD4');
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
